{% set name = "scylla-driver" %}
{% set version = "3.26.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scylla-driver-{{ version }}.tar.gz
  sha256: 3fcc2b2945dd29254a1736614351bcc44c7dbd818dc6fdbf9eb1952b1d72bfc0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.20,!=0.25,<0.30
    - pip
  run:
    - python
    - six >=1.9
    - geomet >=0.1,<0.3
    - pyyaml >5.0

test:
  imports:
    - cassandra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scylladb/python-driver
  summary: Scylla Driver for Apache Cassandra
  dev_url: https://github.com/scylladb/python-driver/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cclinet
