{% set name = "scylla-driver" %}
{% set version = "3.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c4a31433482aaf50d17a6b5f51f1e2a997eaad7be58bca9d6de1e46edc4f2543

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=0.20,!=0.25,<0.30
    - pip
  run:
    - python
    - six >=1.9
    - geomet >=0.1,<0.3
    - pyyaml >5.0

test:
  imports:
    - cassandra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scylladb/python-driver
  summary: Scylla Driver for Apache Cassandra
  dev_url: https://github.com/scylladb/python-driver/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cclinet
